# Generated by Django 4.1.7 on 2023-02-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('subscription_delay_from', models.DateField(auto_now_add=True)),
                ('subscription_delay', models.DateField()),
                ('access_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration1', models.TimeField(null=True)),
                ('duration2', models.TimeField(null=True)),
                ('program', models.CharField(default='open', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], default='friday', max_length=50)),
                ('programSche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.programtab')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_management')),
                ('fullname', models.CharField(max_length=50)),
                ('city', models.CharField(default='algeries', max_length=25)),
                ('email', models.EmailField(default='user@user.com', max_length=254)),
                ('ingym', models.BooleanField(default=False)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.addathlete')),
            ],
        ),
    ]
