# Generated by Django 3.1.7 on 2023-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
            ],
        ),
    ]
