# Generated by Django 4.1.7 on 2023-02-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0002_addathlete_programtab_alter_userprofile_id_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
