# Generated by Django 4.1.7 on 2023-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='image',
            field=models.ImageField(default=1, upload_to='image_management', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='management',
            name='ingym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='management',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
