# Generated by Django 4.1.7 on 2023-02-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_programtab_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programtab',
            name='user',
        ),
    ]
