# Generated by Django 3.1.7 on 2023-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20230509_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='last_access',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='management',
            name='limitation',
            field=models.IntegerField(default=2),
        ),
    ]
