# Generated by Django 3.1.7 on 2023-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20230521_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='accessed',
            field=models.IntegerField(default=0),
        ),
    ]
